# Generated by Django 2.1.1 on 2018-11-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('play_time', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=0)),
                ('max_team', models.IntegerField(default=0)),
                ('reward', models.CharField(max_length=100)),
                ('admin_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user', to='snuslam.User'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result',
            field=models.ManyToManyField(related_name='tournament_result_teams', to='snuslam.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournament_teams', to='snuslam.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snuslam.User'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_users', to='snuslam.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.ManyToManyField(related_name='room_users', to='snuslam.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user', to='snuslam.User'),
        ),
    ]
