# Generated by Django 2.1.2 on 2018-12-02 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('team', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('play_time', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('guests', models.ManyToManyField(related_name='room_users', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members_id', models.ManyToManyField(related_name='team_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('game_type', models.IntegerField(default=0)),
                ('total_team', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('reward', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user', to=settings.AUTH_USER_MODEL)),
                ('result1', models.ManyToManyField(related_name='tournament_result1', to='snuslam.Team')),
                ('result2', models.ManyToManyField(related_name='tournament_result2', to='snuslam.Team')),
                ('result3', models.ManyToManyField(related_name='tournament_result3', to='snuslam.Team')),
                ('teams', models.ManyToManyField(related_name='tournament_teams', to='snuslam.Team')),
            ],
        ),
    ]
