# Generated by Django 2.1.1 on 2018-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuslam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='host',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
