# Generated by Django 2.1.1 on 2018-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuslam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='leader',
            new_name='leader_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='members',
            new_name='members_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='type',
            new_name='game_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='teams_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='result1',
            field=models.ManyToManyField(related_name='tournament_result1', to='snuslam.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result2',
            field=models.ManyToManyField(related_name='tournament_result2', to='snuslam.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result3',
            field=models.ManyToManyField(related_name='tournament_result3', to='snuslam.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_team',
            field=models.IntegerField(default=0),
        ),
    ]
