# Generated by Django 2.1.1 on 2018-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuslam', '0009_profile_teams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
