# Generated by Django 2.1.2 on 2018-12-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snuslam', '0010_profile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creation_time',
        ),
    ]
